lib/mytube_web/router.ex
defmodule MytubeWeb.Router do
  use MytubeWeb, :router

  pipeline :auth do
    plug MytubeWeb.Plugs.RequireAuth
  end
  
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MytubeWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", MytubeWeb do
    pipe_through :browser

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
  end

  scope "/", MytubeWeb do
    pipe_through [:browser, :auth]

    resources "/videos", VideoController, only: [:new, :create]
  end
  
  scope "/", MytubeWeb do
    pipe_through :browser # Use the default browser stack
    resources "/videos", VideoController, only: [:index, :show, :delete, :update]
    get "/", PageController, :index
  end

end

lib/mytube_web/views/layout_view.ex
defmodule MytubeWeb.LayoutView do
  use MytubeWeb, :view
end

lib/mytube_web/templates/layout/_navigation.html.eex
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=<%= page_path(@conn, :index) %>>My Tube</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <%= if @conn.assigns.user do %>


      
      <li class="nav-item">
	<span class="navbar-text">
	  Welcome, <%= @conn.assigns.user.first_name %>!
	</span>
      </li>
      <li class="nav-item">
	<%= link "Videos", class: "nav-link", to: video_path(@conn, :index) %>
      </li>
      <li class="nav-item">
	<%= link "Add video", class: "nav-link", to: video_path(@conn, :new) %>
      </li>
      <li class="nav-item">
	<%= link "Sign out", to: auth_path(@conn, :delete), class: "nav-link"  %>
      </li>


      
      <% else %>


      <li class="nav-item">
	<%= link "Videos", class: "nav-link", to: video_path(@conn, :index) %>
      </li>      
      <li class="nav-item">
	<%= link "Sign in with Google", to: auth_path(@conn, :request, "google"), class: "nav-link"  %>
      </li>


      
      <% end %>
      
    </ul>
  </div>
</nav>

lib/mytube_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
    
    <title>Hello Mytube!</title>
    <!-- Bootstrap CSS -->
    <link
       rel="stylesheet"
       href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
       integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
       crossorigin="anonymous">
    <link
       rel="stylesheet"
       href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <%= render "_navigation.html", conn: @conn %>

      <div class="callout alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>
      <div class="callout alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></div>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
       src="https://code.jquery.com/jquery-3.3.1.min.js"
       integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
       crossorigin="anonymous"></script>    
    <script
       src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
       integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
       crossorigin="anonymous"></script>
    <script
       src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
       integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
       crossorigin="anonymous"></script>
    <script
       src="<%= static_path(@conn, "/js/app.js") %>"></script>
    
  </body>
</html>